"""Initial schema: PostGIS tables, indexes and the privacy-fence functions.

Written by hand rather than autogenerated, because three things in here are not
expressible through the ORM and are exactly the things that must not be wrong:
the geography-based fence buffer, the endpoint jitter, and the trigram index
used for CJK place-name search.

Revision ID: 0001
Revises:
"""

from __future__ import annotations

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels = None
depends_on = None


SCHEMA = r"""
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;      -- CJK place-name search; see below

-- ── Users (MVP has exactly one row; multi-user is reserved) ──────────
CREATE TABLE app_user (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email         text UNIQUE,
    password_hash text,
    display_name  text,
    default_tz    text NOT NULL DEFAULT 'UTC',
    settings      jsonb NOT NULL DEFAULT '{}',
    created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TYPE source_type AS ENUM (
    'photo','google_records','google_semantic','google_timeline',
    'gpx','tcx','fit','manual');

CREATE TABLE source_file (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    kind          source_type NOT NULL,
    display_name  text NOT NULL,
    content_hash  bytea NOT NULL,
    byte_size     bigint,
    storage_key   text,
    status        text NOT NULL DEFAULT 'pending',
    error_detail  jsonb,
    stats         jsonb NOT NULL DEFAULT '{}',
    imported_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, content_hash)             -- L1 dedup
);

-- ── Groups and tags ─────────────────────────────────────────────────
CREATE TYPE group_kind AS ENUM ('user','system_commute');

CREATE TABLE "group" (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    name       text NOT NULL,
    kind       group_kind NOT NULL DEFAULT 'user',
    color      text,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, name)
);

CREATE TABLE tag (
    id      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    name    text NOT NULL,
    color   text,
    UNIQUE (user_id, name)
);

-- ── Raw points (deliberately not partitioned) ───────────────────────
CREATE TYPE point_confidence AS ENUM ('measured','inferred','manual');

CREATE TABLE raw_point (
    id             bigserial PRIMARY KEY,
    user_id        uuid NOT NULL,
    source_file_id uuid NOT NULL REFERENCES source_file(id) ON DELETE CASCADE,
    source_kind    source_type NOT NULL,
    ts_utc         timestamptz NOT NULL,
    tz_name        text,
    geom           geometry(Point,4326) NOT NULL,
    altitude_m     real,
    accuracy_m     real,
    speed_mps      real,
    heading_deg    real,
    confidence     point_confidence NOT NULL DEFAULT 'measured',
    dedup_key      bytea NOT NULL,
    raw            jsonb
);
CREATE UNIQUE INDEX ix_raw_point_user_dedup ON raw_point (user_id, dedup_key);
CREATE INDEX ix_raw_point_geom ON raw_point USING GIST (geom);
CREATE INDEX ix_raw_point_user_ts ON raw_point (user_id, ts_utc);
CREATE INDEX ix_raw_point_user_source ON raw_point (user_id, source_file_id);

-- ── Trips (one per local day) ───────────────────────────────────────
CREATE TYPE commute_class AS ENUM ('pure','mixed','none');

CREATE TABLE trip (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    title          text NOT NULL,
    local_date     date NOT NULL,
    anchor_tz      text NOT NULL,
    start_utc      timestamptz NOT NULL,
    end_utc        timestamptz NOT NULL,
    group_id       uuid REFERENCES "group"(id) ON DELETE SET NULL,
    commute_class  commute_class NOT NULL DEFAULT 'none',
    bbox           geometry(Polygon,4326),
    cover_photo_id uuid,
    stats          jsonb NOT NULL DEFAULT '{}',
    is_auto        boolean NOT NULL DEFAULT true,
    UNIQUE (user_id, local_date)
);
CREATE INDEX ix_trip_user_date ON trip (user_id, local_date DESC);
CREATE INDEX ix_trip_bbox ON trip USING GIST (bbox);
CREATE INDEX ix_trip_group ON trip (group_id);

CREATE TABLE trip_tag (
    trip_id uuid REFERENCES trip(id) ON DELETE CASCADE,
    tag_id  uuid REFERENCES tag(id)  ON DELETE CASCADE,
    PRIMARY KEY (trip_id, tag_id)
);

-- ── Place anchors (derived index, recomputable at any time) ─────────
CREATE TYPE anchor_kind AS ENUM ('home','work','frequent','other');

CREATE TABLE place_anchor (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id          uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    centroid         geometry(Point,4326) NOT NULL,
    radius_m         real,
    visit_count      integer NOT NULL DEFAULT 0,
    first_visit_utc  timestamptz,
    last_visit_utc   timestamptz,
    total_duration_s bigint NOT NULL DEFAULT 0,
    hour_histogram   integer[] NOT NULL DEFAULT '{}',
    weekday_ratio    real,
    kind             anchor_kind NOT NULL DEFAULT 'other',
    kind_source      text,
    geo_name text, geo_city text, geo_region text, geo_country text
);
CREATE INDEX ix_place_anchor_centroid ON place_anchor USING GIST (centroid);
-- to_tsvector('simple', ...) does not segment CJK: searching for the two-character
-- form of "Kyoto" fails to match the three-character city name. Trigram + ILIKE
-- does match. Verified on this machine by scripts/verify_env.py.
CREATE INDEX ix_place_anchor_name_trgm ON place_anchor USING GIN (
    (coalesce(geo_name,'')||' '||coalesce(geo_city,'')||' '||coalesce(geo_country,''))
    gin_trgm_ops);

-- ── Places ──────────────────────────────────────────────────────────
CREATE TABLE place (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      uuid NOT NULL,
    trip_id      uuid REFERENCES trip(id) ON DELETE SET NULL,
    anchor_id    uuid REFERENCES place_anchor(id) ON DELETE SET NULL,
    group_id     uuid REFERENCES "group"(id) ON DELETE SET NULL,
    centroid     geometry(Point,4326) NOT NULL,
    radius_m     real,
    start_utc    timestamptz NOT NULL,
    end_utc      timestamptz NOT NULL,
    duration_s   integer GENERATED ALWAYS AS
                   (EXTRACT(EPOCH FROM (end_utc - start_utc))::int) STORED,
    origin       text NOT NULL DEFAULT 'track',
    google_place_id text,
    is_inferred_dwell boolean NOT NULL DEFAULT false,
    inferred_ratio    real    NOT NULL DEFAULT 0,
    tz_name      text,
    point_count  integer NOT NULL DEFAULT 0,
    name         text,
    geo_name text, geo_city text, geo_region text, geo_country text,
    geo_source   text,
    source_kinds source_type[] NOT NULL DEFAULT '{}'
);
CREATE INDEX ix_place_centroid ON place USING GIST (centroid);
CREATE INDEX ix_place_user_start ON place (user_id, start_utc);
CREATE INDEX ix_place_trip ON place (trip_id);
CREATE INDEX ix_place_anchor ON place (anchor_id);
CREATE INDEX ix_place_name_trgm ON place USING GIN (
    (coalesce(name,'')||' '||coalesce(geo_name,'')||' '||coalesce(geo_city,''))
    gin_trgm_ops);

CREATE TABLE place_tag (
    place_id uuid REFERENCES place(id) ON DELETE CASCADE,
    tag_id   uuid REFERENCES tag(id)   ON DELETE CASCADE,
    PRIMARY KEY (place_id, tag_id)
);

-- ── Tracks ──────────────────────────────────────────────────────────
CREATE TYPE travel_mode AS ENUM
    ('walk','run','bike','car','transit','flight','unknown');

CREATE TABLE track (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         uuid NOT NULL,
    trip_id         uuid REFERENCES trip(id) ON DELETE SET NULL,
    geom            geometry(LineString,4326) NOT NULL,
    start_utc       timestamptz NOT NULL,
    end_utc         timestamptz NOT NULL,
    distance_m      double precision,
    distance_unknown boolean NOT NULL DEFAULT false,
    geom_quality    text NOT NULL DEFAULT 'full',
    duration_s      integer NOT NULL,
    speed_median_mps real,
    speed_p95_mps   real,
    elevation_gain_m real,
    mode            travel_mode NOT NULL DEFAULT 'unknown',
    mode_source     text,
    mode_confidence real,
    point_count     integer,
    is_shadow       boolean NOT NULL DEFAULT false,
    is_commute      boolean NOT NULL DEFAULT false,
    commute_od_id   uuid,
    crosses_tz      boolean NOT NULL DEFAULT false,
    source_kind     source_type NOT NULL
);
CREATE INDEX ix_track_geom ON track USING GIST (geom);
CREATE INDEX ix_track_user_start ON track (user_id, start_utc);
CREATE INDEX ix_track_trip ON track (trip_id) WHERE NOT is_shadow;
CREATE INDEX ix_track_commute ON track (user_id, is_commute) WHERE is_commute;

-- ── Commute OD pairs ────────────────────────────────────────────────
CREATE TABLE commute_od (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    from_anchor_id uuid NOT NULL REFERENCES place_anchor(id) ON DELETE CASCADE,
    to_anchor_id   uuid NOT NULL REFERENCES place_anchor(id) ON DELETE CASCADE,
    occurrence     integer NOT NULL,
    weekday_ratio  real,
    depart_hour_mean real,
    depart_hour_circstd real,
    path_jaccard   real,
    evidence       jsonb NOT NULL DEFAULT '{}'
);
CREATE INDEX ix_commute_od_user ON commute_od (user_id);

-- ── Photos ──────────────────────────────────────────────────────────
CREATE TABLE photo (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             uuid NOT NULL,
    trip_id             uuid REFERENCES trip(id) ON DELETE SET NULL,
    place_id            uuid REFERENCES place(id) ON DELETE SET NULL,
    geom                geometry(Point,4326),
    taken_at_utc        timestamptz,
    taken_at_local      timestamp,
    tz_name             text,
    tz_source           text,
    location_confidence point_confidence,
    place_centroid      geometry(Point,4326),
    place_name          text,
    trip_place_id       uuid REFERENCES place(id) ON DELETE SET NULL,
    thumb_key           text,
    micro_key           text,
    orig_path           text,
    orig_filename       text,
    content_hash        bytea NOT NULL,
    width integer, height integer,
    camera_make text, camera_model text,
    UNIQUE (user_id, content_hash)
);
CREATE INDEX ix_photo_geom ON photo USING GIST (geom);
CREATE INDEX ix_photo_user_taken ON photo (user_id, taken_at_utc);
CREATE INDEX ix_photo_trip ON photo (trip_id);
CREATE INDEX ix_photo_place ON photo (place_id);

CREATE TABLE photo_source (
    photo_id       uuid REFERENCES photo(id) ON DELETE CASCADE,
    source_file_id uuid REFERENCES source_file(id) ON DELETE CASCADE,
    PRIMARY KEY (photo_id, source_file_id)
);

-- ── Privacy fences ──────────────────────────────────────────────────
CREATE TYPE fence_kind AS ENUM ('home','work');

CREATE TABLE geofence (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    kind        fence_kind NOT NULL,
    label       text NOT NULL,
    visit_count integer,
    first_visit_utc timestamptz,
    last_visit_utc  timestamptz,
    center      geometry(Point,4326) NOT NULL,
    radius_m    real NOT NULL DEFAULT 500,
    jitter_seed bigint NOT NULL,
    buffer_geom geometry(Polygon,4326),
    enabled     boolean NOT NULL DEFAULT true
);
CREATE INDEX ix_geofence_center ON geofence USING GIST (center);

-- ── Geocode cache ───────────────────────────────────────────────────
CREATE TABLE geocode_cache (
    geohash7   varchar(12) PRIMARY KEY,
    name text, city text, region text, country text,
    provider   text NOT NULL,
    fetched_at timestamptz NOT NULL DEFAULT now()
);

-- ── Task bookkeeping ────────────────────────────────────────────────
CREATE TABLE import_task (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    kind          text NOT NULL,
    display_name  text NOT NULL,
    status        text NOT NULL DEFAULT 'queued',
    stage         text,
    processed     bigint NOT NULL DEFAULT 0,
    total         bigint,
    options       jsonb NOT NULL DEFAULT '{}',
    result        jsonb NOT NULL DEFAULT '{}',
    error_detail  jsonb,
    created_at    timestamptz NOT NULL DEFAULT now(),
    finished_at   timestamptz
);
CREATE INDEX ix_import_task_user ON import_task (user_id, created_at DESC);

CREATE TABLE export_task (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    status       text NOT NULL DEFAULT 'queued',
    params       jsonb NOT NULL DEFAULT '{}',
    storage_key  text,
    error_detail jsonb,
    created_at   timestamptz NOT NULL DEFAULT now(),
    finished_at  timestamptz
);
CREATE INDEX ix_export_task_user ON export_task (user_id, created_at DESC);

-- Row-level security is intentionally NOT enabled: the MVP is single-user and
-- local, so a policy would only add a way to break background jobs. When
-- multi-user is switched on, three details decide whether it actually works:
--   ALTER TABLE place ENABLE ROW LEVEL SECURITY;
--   ALTER TABLE place FORCE  ROW LEVEL SECURITY;   -- without FORCE the owner bypasses it
--   CREATE POLICY place_isolation ON place
--       USING (user_id = current_setting('app.current_user_id', true)::uuid);
--                                                            ^^^^ two-arg form:
--       returns NULL instead of raising when unset, otherwise workers, health
--       checks and migrations all crash.
-- and the application must connect as a non-owner role.
"""


FENCE_FUNCTIONS = r"""
-- Deterministic pseudo-random in [0,1) from (seed, index).
-- 7 hex chars = 28 bits, so the int cast is always positive.
CREATE OR REPLACE FUNCTION contrail_seeded_unit(seed bigint, idx integer)
RETURNS double precision AS $$
    SELECT (('x0' || substr(md5(seed::text || ':' || idx::text), 1, 7))::bit(32)::int
            % 1000000)::double precision / 1000000.0;
$$ LANGUAGE sql IMMUTABLE;

-- Union of all enabled fences for a user.
--
-- The second argument of the GEOGRAPHY overload of ST_Buffer is in METRES.
-- The degree conversion used before (radius_m / 111320.0) is a LATITUDE-degree
-- conversion, so the east-west extent shrinks with latitude: a "500 m" fence is
-- 384 m wide in Beijing, 287 m in Moscow, 250 m in Oslo. Points 400 m east of
-- home would have been exported in the clear while the user believed they were
-- protected.
CREATE OR REPLACE FUNCTION contrail_fence_buffer(uid uuid)
RETURNS geometry AS $$
    SELECT ST_Union(ST_Buffer(f.center::geography, f.radius_m)::geometry)
    FROM geofence f WHERE f.user_id = uid AND f.enabled;
$$ LANGUAGE sql STABLE;

-- Pull each cut end back along the line by a seeded 0 .. 0.3*R.
--
-- Without this, every break point lies exactly on the fence circle. Export 20
-- images from different days, collect 20 break points, fit a circle through any
-- three of them and the centre - the home - is recovered to within metres. An
-- un-jittered fence does not merely fail to protect: it marks the spot.
CREATE OR REPLACE FUNCTION contrail_jitter_endpoints(g geometry, uid uuid)
RETURNS geometry AS $$
DECLARE
    buf      geometry;
    edge     geometry;
    comp     geometry;
    parts    geometry[] := '{}';
    n        integer;
    i        integer;
    len      double precision;
    r        double precision;
    seed     bigint;
    head     double precision;
    tail     double precision;
    trimmed  geometry;
BEGIN
    IF g IS NULL OR ST_IsEmpty(g) THEN
        RETURN g;
    END IF;

    buf := contrail_fence_buffer(uid);
    IF buf IS NULL THEN
        RETURN g;
    END IF;
    edge := ST_Boundary(buf);

    SELECT COALESCE(max(f.radius_m), 500), COALESCE(min(f.jitter_seed), 0)
      INTO r, seed
      FROM geofence f WHERE f.user_id = uid AND f.enabled;

    n := COALESCE(ST_NumGeometries(g), 1);
    FOR i IN 1..n LOOP
        comp := COALESCE(ST_GeometryN(g, i), g);
        IF GeometryType(comp) <> 'LINESTRING' THEN
            parts := parts || comp;
            CONTINUE;
        END IF;

        len := ST_Length(comp::geography);
        IF len IS NULL OR len < 1 THEN
            CONTINUE;                                  -- degenerate stub, drop it
        END IF;

        head := 0;
        tail := 0;
        -- 1 m tolerance: only ends produced by the cut sit on the fence edge.
        IF ST_DWithin(ST_StartPoint(comp)::geography, edge::geography, 1.0) THEN
            head := r * 0.3 * contrail_seeded_unit(seed, i * 2);
        END IF;
        IF ST_DWithin(ST_EndPoint(comp)::geography, edge::geography, 1.0) THEN
            tail := r * 0.3 * contrail_seeded_unit(seed, i * 2 + 1);
        END IF;

        IF head + tail >= len THEN
            CONTINUE;                                  -- nothing survives the trim
        END IF;

        trimmed := ST_LineSubstring(comp, head / len, 1.0 - tail / len);
        IF trimmed IS NOT NULL AND NOT ST_IsEmpty(trimmed) THEN
            parts := parts || trimmed;
        END IF;
    END LOOP;

    IF array_length(parts, 1) IS NULL THEN
        RETURN NULL;
    END IF;
    RETURN ST_Multi(ST_Collect(parts));
END;
$$ LANGUAGE plpgsql STABLE;

-- Policy A - remove: cut the geometry out, then jitter the resulting ends.
CREATE OR REPLACE FUNCTION contrail_fence_remove(g geometry, uid uuid)
RETURNS geometry AS $$
    SELECT contrail_jitter_endpoints(
        COALESCE(ST_Difference(g, contrail_fence_buffer(uid)), g), uid);
$$ LANGUAGE sql STABLE;

-- Policy B - blur: quantise to a grid. Deliberately not random noise, which
-- averages away over repeated exports; a grid does not.
--
-- Snapping ALONE does not satisfy the invariant, and the regression test proves
-- it: a 2 km grid node can fall arbitrarily close to the fence centre, and one
-- measured 386 m from it - well inside a 500 m fence. Quantisation coarsens
-- precision; it does not guarantee exclusion. So the residue is cut as well.
--
-- What still distinguishes blur from remove: blur quantises the WHOLE geometry,
-- so the surrounding track is coarse too and the gap is not sharply located.
-- Remove keeps full precision right up to the fence edge and cuts only there.
CREATE OR REPLACE FUNCTION contrail_fence_blur(g geometry, uid uuid, grid_m integer DEFAULT 2000)
RETURNS geometry AS $$
DECLARE
    buf     geometry;
    snapped geometry;
    cleaned geometry;
BEGIN
    IF g IS NULL OR ST_IsEmpty(g) THEN
        RETURN g;
    END IF;

    buf := contrail_fence_buffer(uid);
    IF buf IS NULL OR NOT ST_Intersects(g, buf) THEN
        RETURN g;
    END IF;

    snapped := ST_SnapToGrid(g, grid_m / 111320.0);
    -- Snapping can collapse a line's vertices onto one another; if that leaves
    -- nothing drawable, fall back to the original and let the cut do the work.
    IF snapped IS NULL OR ST_IsEmpty(snapped)
       OR (GeometryType(snapped) LIKE '%LINESTRING%' AND ST_NPoints(snapped) < 2) THEN
        snapped := g;
    END IF;

    cleaned := ST_Difference(snapped, buf);
    IF cleaned IS NULL OR ST_IsEmpty(cleaned) THEN
        RETURN NULL;
    END IF;
    RETURN contrail_jitter_endpoints(cleaned, uid);
END;
$$ LANGUAGE plpgsql STABLE;

-- Entry point used by the tile SQL. In the MVP the tile endpoint always passes
-- apply_fence = false (export is the only enforcement point), but the call site
-- exists so cloud mode only has to flip the flag.
CREATE OR REPLACE FUNCTION contrail_apply_fence(g geometry, uid uuid)
RETURNS geometry AS $$
    SELECT contrail_fence_remove(g, uid);
$$ LANGUAGE sql STABLE;

-- Materialise geofence.buffer_geom on write. Fences number in the single
-- digits, so recomputing on change is far cheaper than buffering per query.
CREATE OR REPLACE FUNCTION contrail_geofence_buffer_trg() RETURNS trigger AS $$
BEGIN
    NEW.buffer_geom := ST_Buffer(NEW.center::geography, NEW.radius_m)::geometry;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER geofence_buffer_biu
    BEFORE INSERT OR UPDATE OF center, radius_m ON geofence
    FOR EACH ROW EXECUTE FUNCTION contrail_geofence_buffer_trg();
"""


DROP = r"""
DROP TRIGGER IF EXISTS geofence_buffer_biu ON geofence;
DROP FUNCTION IF EXISTS contrail_geofence_buffer_trg();
DROP FUNCTION IF EXISTS contrail_apply_fence(geometry, uuid);
DROP FUNCTION IF EXISTS contrail_fence_blur(geometry, uuid, integer);
DROP FUNCTION IF EXISTS contrail_fence_remove(geometry, uuid);
DROP FUNCTION IF EXISTS contrail_jitter_endpoints(geometry, uuid);
DROP FUNCTION IF EXISTS contrail_fence_buffer(uuid);
DROP FUNCTION IF EXISTS contrail_seeded_unit(bigint, integer);

DROP TABLE IF EXISTS export_task, import_task, geocode_cache, geofence,
    photo_source, photo, commute_od, track, place_tag, place, place_anchor,
    trip_tag, trip, raw_point, tag, "group", source_file, app_user CASCADE;

DROP TYPE IF EXISTS fence_kind, travel_mode, commute_class, anchor_kind,
    point_confidence, group_kind, source_type;
"""


def upgrade() -> None:
    op.execute(SCHEMA)
    op.execute(FENCE_FUNCTIONS)


def downgrade() -> None:
    op.execute(DROP)
